# Generated by Django 4.2.6 on 2023-12-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_paintingrequest_custom_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='paintingrequest',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email'),
        ),
    ]
