# Generated by Django 4.2.6 on 2023-12-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_paintingrequest_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paintingrequest',
            name='examples',
            field=models.ImageField(blank=True, null=True, upload_to='painting_examples/', verbose_name='File with examples:'),
        ),
    ]
