# Generated by Django 4.1 on 2023-12-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_paintingrequest_examples'),
    ]

    operations = [
        migrations.AddField(
            model_name='paintingrequest',
            name='examples2',
            field=models.ImageField(blank=True, null=True, upload_to='painting_examples/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='paintingrequest',
            name='examples',
            field=models.ImageField(blank=True, null=True, upload_to='painting_examples/', verbose_name='Files with examples:'),
        ),
    ]
