# Generated by Django 4.1 on 2023-12-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_paintingrequest_examples2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryPaintingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
