# Generated by Django 4.1 on 2023-12-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_temporarypaintingrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarypaintingrequest',
            name='add_signature',
            field=models.BooleanField(default=True, verbose_name='Add artist signature'),
        ),
        migrations.AddField(
            model_name='temporarypaintingrequest',
            name='description',
            field=models.TextField(default='', verbose_name='Description of the painting'),
        ),
        migrations.AddField(
            model_name='temporarypaintingrequest',
            name='examples',
            field=models.ImageField(blank=True, null=True, upload_to='painting_examples/', verbose_name='Files with examples:'),
        ),
        migrations.AddField(
            model_name='temporarypaintingrequest',
            name='examples2',
            field=models.ImageField(blank=True, null=True, upload_to='painting_examples/', verbose_name=''),
        ),
        migrations.AddField(
            model_name='temporarypaintingrequest',
            name='size',
            field=models.CharField(default='', max_length=20, verbose_name='Size of the painting'),
        ),
    ]
