# Generated by Django 4.1 on 2023-12-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_temporarypaintingrequest_add_signature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarypaintingrequest',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Description of the painting'),
        ),
        migrations.AlterField(
            model_name='temporarypaintingrequest',
            name='size',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Size of the painting'),
        ),
    ]
