# Generated by Django 4.1 on 2023-12-30 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0008_alter_temporarypaintingrequest_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paintingrequest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='painting_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
