# Generated by Django 4.1 on 2024-01-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrating',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
